/* createTweakTimeline.svelte.js generated by Svelte v5.53.7 */
import * as $ from 'svelte/internal/server';
import { TweakStore } from '../src/store/TweakStore.ts';

import {
	TimelineStore,
	buildTimelineMeta,
	buildTimelineValues,
	computeStaticTimeline,
	parseTimelineConfig
} from '../src/timeline/index.ts';

let timelineInstance = 0;

export function createTweakTimeline(name, config, options) {
	const hasStableId = options?.id !== undefined;
	const panelId = options?.id ?? `${name}-${++timelineInstance}`;
	const parsed = $.derived(() => parseTimelineConfig(config));
	let flatValues = TweakStore.getValues(panelId);
	let transport = TimelineStore.getTransport(panelId);

	// The active loop window drives phase continuity for looping/sequence clips.
	// Shares the transport notify channel (set/clear region notifies too); the
	// stored region reference is stable so this snapshot never churns.
	let loopRegion = TimelineStore.getLoopRegion(panelId);

	const staticTimeline = $.derived(() => computeStaticTimeline(parsed(), flatValues));

	const actions = {
		play: () => TimelineStore.play(panelId),
		pause: () => TimelineStore.pause(panelId),
		replay: () => TimelineStore.replay(panelId),
		seek: (time) => TimelineStore.seek(panelId, time)
	};

	const resolved = $.derived(() => {
		// No region → loop the whole timeline [0, duration] (the default).
		const loopStart = loopRegion ? loopRegion.start : 0;

		const loopEnd = loopRegion ? loopRegion.end : staticTimeline().duration;

		return buildTimelineValues(staticTimeline().clips, transport, staticTimeline().duration, loopStart, loopEnd, actions);
	});

	return reactiveProxy(() => resolved());
}

function reactiveProxy(read, path = []) {
	const nested = new Map();

	return new Proxy({}, {
		get(_target, key) {
			const value = readPath(read(), [...path, key]);

			if (typeof value !== 'object' || value === null) return value;
			if (!nested.has(key)) nested.set(key, reactiveProxy(read, [...path, key]));

			return nested.get(key);
		},

		ownKeys() {
			const value = readPath(read(), path);

			return typeof value === 'object' && value !== null ? Reflect.ownKeys(value) : [];
		},

		getOwnPropertyDescriptor() {
			return { enumerable: true, configurable: true };
		}
	});
}

function readPath(source, path) {
	return path.reduce(
		(value, key) => {
			if (typeof value !== 'object' || value === null) return undefined;

			return Reflect.get(value, key);
		},
		source
	);
}